CREATE TABLE employees (
    emp_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR2(50),
    last_name     VARCHAR2(50) NOT NULL,
    email         VARCHAR2(100) UNIQUE,
    hire_date     DATE DEFAULT SYSDATE,
    salary        NUMBER(10,2)
);

CREATE TABLE departments (
    dept_id     NUMBER PRIMARY KEY,
    dept_name   VARCHAR2(100) NOT NULL,
    location    VARCHAR2(100)
);

CREATE TABLE products (
    product_id     NUMBER PRIMARY KEY,
    product_name   VARCHAR2(200) NOT NULL,
    price          NUMBER(10,2),
    created_on     DATE DEFAULT SYSDATE
);

CREATE TABLE orders (
    order_id      NUMBER PRIMARY KEY,
    customer_id   NUMBER NOT NULL,
    order_date    DATE DEFAULT SYSDATE,
    status        VARCHAR2(20),
    total_amount  NUMBER(12,2)
);

CREATE TABLE order_items (
    item_id      NUMBER PRIMARY KEY,
    order_id     NUMBER NOT NULL,
    product_id   NUMBER NOT NULL,
    quantity     NUMBER(5) DEFAULT 1,
    price_each   NUMBER(10,2),
    CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE customers (
    customer_id   NUMBER PRIMARY KEY,
    full_name     VARCHAR2(150) NOT NULL,
    phone         VARCHAR2(20),
    email         VARCHAR2(100),
    created_on    DATE DEFAULT SYSDATE
);

CREATE TABLE audit_log (
    log_id        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    table_name    VARCHAR2(50),
    operation     VARCHAR2(10),
    changed_by    VARCHAR2(50),
    changed_on    DATE DEFAULT SYSDATE,
    details       CLOB
);

CREATE TABLE inventory (
    inv_id        NUMBER PRIMARY KEY,
    product_id    NUMBER NOT NULL,
    quantity      NUMBER(10),
    last_updated  DATE DEFAULT SYSDATE,
    CONSTRAINT fk_inv_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE suppliers (
    supplier_id    NUMBER PRIMARY KEY,
    supplier_name  VARCHAR2(200) NOT NULL,
    contact_no     VARCHAR2(20),
    address        VARCHAR2(300)
);

CREATE TABLE product_suppliers (
    product_id    NUMBER NOT NULL,
    supplier_id   NUMBER NOT NULL,
    supply_price  NUMBER(10,2),
    PRIMARY KEY (product_id, supplier_id),
    CONSTRAINT fk_ps_product  FOREIGN KEY (product_id)  REFERENCES products(product_id),
    CONSTRAINT fk_ps_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
);


CREATE TABLE NSEStocks (
    StockName   VARCHAR2(50),
    StockValue  NUMBER(10,2)
);

INSERT INTO NSEStocks VALUES ('Reliance Industries', 2450.75);
INSERT INTO NSEStocks VALUES ('Tata Consultancy Services', 3650.20);
INSERT INTO NSEStocks VALUES ('Infosys', 1525.40);
INSERT INTO NSEStocks VALUES ('HDFC Bank', 1680.10);
INSERT INTO NSEStocks VALUES ('ICICI Bank', 980.55);


INSERT INTO NSEStocks VALUES ('Kotak Mahindra Bank', 1725.30);
INSERT INTO NSEStocks VALUES ('Axis Bank', 1025.80);
INSERT INTO NSEStocks VALUES ('State Bank of India', 625.45);
INSERT INTO NSEStocks VALUES ('Bharti Airtel', 920.60);
INSERT INTO NSEStocks VALUES ('Adani Enterprises', 2450.00);
INSERT INTO NSEStocks VALUES ('Adani Ports', 1150.25);
INSERT INTO NSEStocks VALUES ('Hindustan Unilever', 2450.90);
INSERT INTO NSEStocks VALUES ('ITC', 465.70);
INSERT INTO NSEStocks VALUES ('Larsen & Toubro', 3200.15);
INSERT INTO NSEStocks VALUES ('Maruti Suzuki', 10250.50);
INSERT INTO NSEStocks VALUES ('Mahindra & Mahindra', 1680.75);
INSERT INTO NSEStocks VALUES ('UltraTech Cement', 8900.40);
INSERT INTO NSEStocks VALUES ('Nestle India', 24500.00);
INSERT INTO NSEStocks VALUES ('Wipro', 465.20);
INSERT INTO NSEStocks VALUES ('Power Grid Corp', 245.35);